# =============================================================================
# [DATA FILE ONLY]  (quality_data 패키지로 분리됨)
# 이 파일은 로직이 아니라 '튜닝 테이블/상수'만 담는 **데이터 모듈**입니다.
# 로직 파일: quality.py
# =============================================================================

from __future__ import annotations

from typing import Dict

# group_id -> scheme -> role -> weight (role involvement weights)
GROUP_SCHEME_ROLE_WEIGHTS: Dict[str, Dict[str, Dict[str, float]]] = {'catch_shoot': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                              'Zone_Bottom_Right': 0.2,
                              'Zone_Bottom_Center': 0.2,
                              'Zone_Top_Left': 0.2,
                              'Zone_Top_Right': 0.2},
                 'drop': {'Lowman_Helper': 0.15,
                          'Nail_Helper': 0.25,
                          'PnR_Cover_Big_Drop': 0.1,
                          'PnR_POA_Defender': 0.15,
                          'Weakside_Rotator': 0.35},
                 '블리츠-트랩': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.25,
                            'PnR_Cover_Big_Blitz': 0.15,
                            'PnR_POA_Blitz': 0.1,
                            'Weakside_Rotator': 0.3},
                 '올-스위치': {'Backline_Anchor': 0.2,
                           'PnR_Cover_Big_Switch': 0.15,
                           'PnR_POA_Switch': 0.2,
                           'Switch_Wing_Strong': 0.2,
                           'Switch_Wing_Weak': 0.25},
                 '스위치 1-4': {'Backline_Anchor': 0.25,
                                             'PnR_Cover_Big_Switch_1_4': 0.15,
                                             'PnR_POA_Switch_1_4': 0.2,
                                             'Switch_Wing_Strong_1_4': 0.2,
                                             'Switch_Wing_Weak_1_4': 0.2},
                 '헷지-쇼앤리커버': {'Lowman_Helper': 0.15,
                              'Nail_Helper': 0.25,
                              'PnR_Cover_Big_HedgeRecover': 0.15,
                              'PnR_POA_Defender': 0.15,
                              'Weakside_Rotator': 0.3},
                 '앳-더-레벨': {'Lowman_Helper': 0.15,
                             'Nail_Helper': 0.25,
                             'PnR_Cover_Big_AtTheLevel': 0.15,
                             'PnR_POA_AtTheLevel': 0.15,
                             'Weakside_Rotator': 0.3}},
 'paint_non_rim': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                'Zone_Bottom_Right': 0.2,
                                'Zone_Bottom_Center': 0.25,
                                'Zone_Top_Left': 0.175,
                                'Zone_Top_Right': 0.175},
                   'drop': {'Lowman_Helper': 0.15,
                            'Nail_Helper': 0.2,
                            'PnR_Cover_Big_Drop': 0.2,
                            'PnR_POA_Defender': 0.35,
                            'Weakside_Rotator': 0.1},
                   '블리츠-트랩': {'Lowman_Helper': 0.2,
                              'Nail_Helper': 0.2,
                              'PnR_Cover_Big_Blitz': 0.15,
                              'PnR_POA_Blitz': 0.25,
                              'Weakside_Rotator': 0.2},
                   '올-스위치': {'Backline_Anchor': 0.2,
                             'PnR_Cover_Big_Switch': 0.2,
                             'PnR_POA_Switch': 0.3,
                             'Switch_Wing_Strong': 0.15,
                             'Switch_Wing_Weak': 0.15},
                   '스위치 1-4': {'Backline_Anchor': 0.24,
                                                'PnR_Cover_Big_Switch_1_4': 0.24,
                                                'PnR_POA_Switch_1_4': 0.28,
                                                'Switch_Wing_Strong_1_4': 0.12,
                                                'Switch_Wing_Weak_1_4': 0.12},
                   '헷지-쇼앤리커버': {'Lowman_Helper': 0.2,
                                'Nail_Helper': 0.2,
                                'PnR_Cover_Big_HedgeRecover': 0.25,
                                'PnR_POA_Defender': 0.25,
                                'Weakside_Rotator': 0.1},
                   '앳-더-레벨': {'Lowman_Helper': 0.2,
                                 'Nail_Helper': 0.2,
                                 'PnR_Cover_Big_AtTheLevel': 0.25,
                                 'PnR_POA_AtTheLevel': 0.25,
                                 'Weakside_Rotator': 0.1}},
 'pass_extra': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.26,
                             'Zone_Bottom_Right': 0.26,
                             'Zone_Top_Left': 0.21,
                             'Zone_Bottom_Center': 0.05,
                             'Zone_Top_Right': 0.22},
                'drop': {'Lowman_Helper': 0.15,
                         'Nail_Helper': 0.3,
                         'PnR_Cover_Big_Drop': 0.1,
                         'PnR_POA_Defender': 0.1,
                         'Weakside_Rotator': 0.35},
                '블리츠-트랩': {'Lowman_Helper': 0.2,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_Blitz': 0.05,
                           'PnR_POA_Blitz': 0.1,
                           'Weakside_Rotator': 0.35},
                '올-스위치': {'Backline_Anchor': 0.2,
                          'PnR_Cover_Big_Switch': 0.15,
                          'PnR_POA_Switch': 0.15,
                          'Switch_Wing_Strong': 0.2,
                          'Switch_Wing_Weak': 0.3},
                '스위치 1-4': {'Backline_Anchor': 0.22,
                                         'PnR_Cover_Big_Switch_1_4': 0.15,
                                         'PnR_POA_Switch_1_4': 0.15,
                                         'Switch_Wing_Strong_1_4': 0.18,
                                         'Switch_Wing_Weak_1_4': 0.3},
                '헷지-쇼앤리커버': {'Lowman_Helper': 0.15,
                             'Nail_Helper': 0.3,
                             'PnR_Cover_Big_HedgeRecover': 0.15,
                             'PnR_POA_Defender': 0.1,
                             'Weakside_Rotator': 0.3},
                '앳-더-레벨': {'Lowman_Helper': 0.15,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_AtTheLevel': 0.15,
                            'PnR_POA_AtTheLevel': 0.1,
                            'Weakside_Rotator': 0.3}},
 'pass_kickout': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.22,
                               'Zone_Bottom_Right': 0.22,
                               'Zone_Top_Left': 0.27,
                               'Zone_Bottom_Center': 0.02,
                               'Zone_Top_Right': 0.27},
                  'drop': {'Lowman_Helper': 0.15,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_Drop': 0.1,
                           'PnR_POA_Defender': 0.15,
                           'Weakside_Rotator': 0.3},
                  '블리츠-트랩': {'Lowman_Helper': 0.1,
                             'Nail_Helper': 0.3,
                             'PnR_Cover_Big_Blitz': 0.15,
                             'PnR_POA_Blitz': 0.15,
                             'Weakside_Rotator': 0.3},
                  '올-스위치': {'Backline_Anchor': 0.2,
                            'PnR_Cover_Big_Switch': 0.15,
                            'PnR_POA_Switch': 0.2,
                            'Switch_Wing_Strong': 0.2,
                            'Switch_Wing_Weak': 0.25},
                  '스위치 1-4': {'Backline_Anchor': 0.22,
                                                 'PnR_Cover_Big_Switch_1_4': 0.15,
                                                 'PnR_POA_Switch_1_4': 0.2,
                                                 'Switch_Wing_Strong_1_4': 0.2,
                                                 'Switch_Wing_Weak_1_4': 0.23},
                  '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                               'Nail_Helper': 0.3,
                               'PnR_Cover_Big_HedgeRecover': 0.2,
                               'PnR_POA_Defender': 0.15,
                               'Weakside_Rotator': 0.25},
                   '앳-더-레벨': {'Lowman_Helper': 0.1,
                                 'Nail_Helper': 0.3,
                                 'PnR_Cover_Big_AtTheLevel': 0.22,
                                 'PnR_POA_AtTheLevel': 0.16,
                                 'Weakside_Rotator': 0.22}},
 'pass_shortroll': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                 'Zone_Bottom_Right': 0.2,
                                 'Zone_Top_Left': 0.15,
                                 'Zone_Bottom_Center': 0.3,
                                 'Zone_Top_Right': 0.15},
                    'drop': {'Lowman_Helper': 0.3,
                             'Nail_Helper': 0.25,
                             'PnR_Cover_Big_Drop': 0.2,
                             'PnR_POA_Defender': 0.1,
                             'Weakside_Rotator': 0.15},
                    '블리츠-트랩': {'Lowman_Helper': 0.2,
                               'Nail_Helper': 0.2,
                               'PnR_Cover_Big_Blitz': 0.25,
                               'PnR_POA_Blitz': 0.2,
                               'Weakside_Rotator': 0.15},
                    '올-스위치': {'Backline_Anchor': 0.3,
                              'PnR_Cover_Big_Switch': 0.2,
                              'PnR_POA_Switch': 0.2,
                              'Switch_Wing_Strong': 0.15,
                              'Switch_Wing_Weak': 0.15},
                    '스위치 1-4': {'Backline_Anchor': 0.33,
                                                   'PnR_Cover_Big_Switch_1_4': 0.2,
                                                   'PnR_POA_Switch_1_4': 0.19,
                                                   'Switch_Wing_Strong_1_4': 0.14,
                                                   'Switch_Wing_Weak_1_4': 0.14},
                    '헷지-쇼앤리커버': {'Lowman_Helper': 0.25,
                                 'Nail_Helper': 0.2,
                                 'PnR_Cover_Big_HedgeRecover': 0.25,
                                 'PnR_POA_Defender': 0.15,
                                 'Weakside_Rotator': 0.15},
                     '앳-더-레벨': {'Lowman_Helper': 0.22,
                                   'Nail_Helper': 0.2,
                                   'PnR_Cover_Big_AtTheLevel': 0.28,
                                   'PnR_POA_AtTheLevel': 0.15,
                                   'Weakside_Rotator': 0.15}},
 'pass_skip': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.18,
                            'Zone_Bottom_Right': 0.18,
                            'Zone_Top_Left': 0.28,
                            'Zone_Bottom_Center': 0.08,
                            'Zone_Top_Right': 0.28},
               'drop': {'Lowman_Helper': 0.15,
                        'Nail_Helper': 0.3,
                        'PnR_Cover_Big_Drop': 0.1,
                        'PnR_POA_Defender': 0.15,
                        'Weakside_Rotator': 0.3},
               '블리츠-트랩': {'Lowman_Helper': 0.1,
                          'Nail_Helper': 0.35,
                          'PnR_Cover_Big_Blitz': 0.1,
                          'PnR_POA_Blitz': 0.15,
                          'Weakside_Rotator': 0.3},
               '올-스위치': {'Backline_Anchor': 0.15,
                         'PnR_Cover_Big_Switch': 0.15,
                         'PnR_POA_Switch': 0.15,
                         'Switch_Wing_Strong': 0.25,
                         'Switch_Wing_Weak': 0.3},
               '스위치 1-4': {'Backline_Anchor': 0.18,
                                         'PnR_Cover_Big_Switch_1_4': 0.15,
                                         'PnR_POA_Switch_1_4': 0.15,
                                         'Switch_Wing_Strong_1_4': 0.24,
                                         'Switch_Wing_Weak_1_4': 0.28},
               '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_HedgeRecover': 0.2,
                            'PnR_POA_Defender': 0.1,
                            'Weakside_Rotator': 0.3},
             '앳-더-레벨': {'Lowman_Helper': 0.1,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_AtTheLevel': 0.2,
                           'PnR_POA_AtTheLevel': 0.1,
                           'Weakside_Rotator': 0.3}},
 'pullup': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.15,
                         'Zone_Bottom_Right': 0.15,
                         'Zone_Bottom_Center': 0.1,
                         'Zone_Top_Left': 0.3,
                         'Zone_Top_Right': 0.3},
            'drop': {'Lowman_Helper': 0.05,
                     'Nail_Helper': 0.15,
                     'PnR_Cover_Big_Drop': 0.15,
                     'PnR_POA_Defender': 0.55,
                     'Weakside_Rotator': 0.1},
            '블리츠-트랩': {'Lowman_Helper': 0.1,
                       'Nail_Helper': 0.15,
                       'PnR_Cover_Big_Blitz': 0.25,
                       'PnR_POA_Blitz': 0.35,
                       'Weakside_Rotator': 0.15},
            '올-스위치': {'Backline_Anchor': 0.1,
                      'PnR_Cover_Big_Switch': 0.2,
                      'PnR_POA_Switch': 0.35,
                      'Switch_Wing_Strong': 0.2,
                      'Switch_Wing_Weak': 0.15},
            '스위치 1-4': {'Backline_Anchor': 0.12,
                                   'PnR_Cover_Big_Switch_1_4': 0.22,
                                   'PnR_POA_Switch_1_4': 0.32,
                                   'Switch_Wing_Strong_1_4': 0.19,
                                   'Switch_Wing_Weak_1_4': 0.15},
            '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                         'Nail_Helper': 0.15,
                         'PnR_Cover_Big_HedgeRecover': 0.25,
                         'PnR_POA_Defender': 0.35,
                         'Weakside_Rotator': 0.15},
          '앳-더-레벨': {'Lowman_Helper': 0.08,
                        'Nail_Helper': 0.14,
                        'PnR_Cover_Big_AtTheLevel': 0.28,
                        'PnR_POA_AtTheLevel': 0.38,
                        'Weakside_Rotator': 0.12}},
 'rim_finish': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.25,
                             'Zone_Bottom_Right': 0.25,
                             'Zone_Bottom_Center': 0.3,
                             'Zone_Top_Left': 0.1,
                             'Zone_Top_Right': 0.1},
                'drop': {'Lowman_Helper': 0.25,
                         'Nail_Helper': 0.05,
                         'PnR_Cover_Big_Drop': 0.45,
                         'PnR_POA_Defender': 0.2,
                         'Weakside_Rotator': 0.05},
                '블리츠-트랩': {'Lowman_Helper': 0.3,
                           'Nail_Helper': 0.2,
                           'PnR_Cover_Big_Blitz': 0.15,
                           'PnR_POA_Blitz': 0.15,
                           'Weakside_Rotator': 0.2},
                '올-스위치': {'Backline_Anchor': 0.35,
                          'PnR_Cover_Big_Switch': 0.2,
                          'PnR_POA_Switch': 0.2,
                          'Switch_Wing_Strong': 0.1,
                          'Switch_Wing_Weak': 0.15},
                '스위치 1-4': {'Backline_Anchor': 0.4,
                                          'PnR_Cover_Big_Switch_1_4': 0.22,
                                          'PnR_POA_Switch_1_4': 0.18,
                                          'Switch_Wing_Strong_1_4': 0.08,
                                          'Switch_Wing_Weak_1_4': 0.12},
                '헷지-쇼앤리커버': {'Lowman_Helper': 0.25,
                             'Nail_Helper': 0.15,
                             'PnR_Cover_Big_HedgeRecover': 0.3,
                             'PnR_POA_Defender': 0.2,
                             'Weakside_Rotator': 0.1},
             '앳-더-레벨': {'Lowman_Helper': 0.25,
                           'Nail_Helper': 0.15,
                           'PnR_Cover_Big_AtTheLevel': 0.32,
                           'PnR_POA_AtTheLevel': 0.18,
                           'Weakside_Rotator': 0.1}},
 'to_charge': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                            'Zone_Bottom_Right': 0.2,
                            'Zone_Bottom_Center': 0.2,
                            'Zone_Top_Left': 0.2,
                            'Zone_Top_Right': 0.2},
               'drop': {'Lowman_Helper': 0.2,
                        'Nail_Helper': 0.3,
                        'PnR_Cover_Big_Drop': 0.1,
                        'PnR_POA_Defender': 0.35,
                        'Weakside_Rotator': 0.05},
               '블리츠-트랩': {'Lowman_Helper': 0.2,
                          'Nail_Helper': 0.35,
                          'PnR_Cover_Big_Blitz': 0.1,
                          'PnR_POA_Blitz': 0.25,
                          'Weakside_Rotator': 0.1},
               '올-스위치': {'Backline_Anchor': 0.25,
                         'PnR_Cover_Big_Switch': 0.1,
                         'PnR_POA_Switch': 0.3,
                         'Switch_Wing_Strong': 0.2,
                         'Switch_Wing_Weak': 0.15},
               '스위치 1-4': {'Backline_Anchor': 0.27,
                                         'PnR_Cover_Big_Switch_1_4': 0.1,
                                         'PnR_POA_Switch_1_4': 0.29,
                                         'Switch_Wing_Strong_1_4': 0.2,
                                         'Switch_Wing_Weak_1_4': 0.14},
               '헷지-쇼앤리커버': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_HedgeRecover': 0.1,
                            'PnR_POA_Defender': 0.3,
                            'Weakside_Rotator': 0.1},
            '앳-더-레벨': {'Lowman_Helper': 0.18,
                          'Nail_Helper': 0.3,
                          'PnR_Cover_Big_AtTheLevel': 0.12,
                          'PnR_POA_AtTheLevel': 0.3,
                          'Weakside_Rotator': 0.1}},
 'to_handle_loss': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                 'Zone_Bottom_Right': 0.2,
                                 'Zone_Bottom_Center': 0.1,
                                 'Zone_Top_Left': 0.25,
                                 'Zone_Top_Right': 0.25},
                    'drop': {'Lowman_Helper': 0.05,
                             'Nail_Helper': 0.15,
                             'PnR_Cover_Big_Drop': 0.1,
                             'PnR_POA_Defender': 0.6,
                             'Weakside_Rotator': 0.1},
                    '블리츠-트랩': {'Lowman_Helper': 0.05,
                               'Nail_Helper': 0.15,
                               'PnR_Cover_Big_Blitz': 0.3,
                               'PnR_POA_Blitz': 0.45,
                               'Weakside_Rotator': 0.05},
                    '올-스위치': {'Backline_Anchor': 0.1,
                              'PnR_Cover_Big_Switch': 0.2,
                              'PnR_POA_Switch': 0.4,
                              'Switch_Wing_Strong': 0.2,
                              'Switch_Wing_Weak': 0.1},
                    '스위치 1-4': {'Backline_Anchor': 0.12,
                                                   'PnR_Cover_Big_Switch_1_4': 0.2,
                                                   'PnR_POA_Switch_1_4': 0.38,
                                                   'Switch_Wing_Strong_1_4': 0.2,
                                                   'Switch_Wing_Weak_1_4': 0.1},
                    '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                                 'Nail_Helper': 0.15,
                                 'PnR_Cover_Big_HedgeRecover': 0.2,
                                 'PnR_POA_Defender': 0.45,
                                 'Weakside_Rotator': 0.1},
              '앳-더-레벨': {'Lowman_Helper': 0.08,
                            'Nail_Helper': 0.15,
                            'PnR_Cover_Big_AtTheLevel': 0.22,
                            'PnR_POA_AtTheLevel': 0.45,
                            'Weakside_Rotator': 0.1}}}
