# =============================================================================
# [DATA FILE ONLY]  (quality_data 패키지로 분리됨)
# 이 파일은 로직이 아니라 '튜닝 테이블/상수'만 담는 **데이터 모듈**입니다.
# 로직 파일: quality.py
# =============================================================================

from __future__ import annotations

from typing import Dict

# scheme -> role -> stat_profile (stat -> weight)
ROLE_STAT_PROFILES: Dict[str, Dict[str, Dict[str, float]]] = {'2-3 존디펜스': {'Zone_Bottom_Left': {'DEF_HELP': 0.15,
                                   'DEF_POST': 0.15,
                                   'DEF_RIM': 0.3,
                                   'ENDURANCE': 0.05,
                                   'PHYSICAL': 0.1,
                                   'REB_DR': 0.25},
              'Zone_Bottom_Right': {'DEF_HELP': 0.15,
                                    'DEF_POST': 0.15,
                                    'DEF_RIM': 0.3,
                                    'ENDURANCE': 0.05,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.25},
              'Zone_Bottom_Center': {'DEF_HELP': 0.10,
                                    'DEF_POST': 0.2,
                                    'DEF_RIM': 0.3,
                                    'ENDURANCE': 0.05,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.25},
              'Zone_Top_Left': {'DEF_HELP': 0.3, 'DEF_POA': 0.25, 'DEF_STEAL': 0.2, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
              'Zone_Top_Right': {'DEF_HELP': 0.3,
                                 'DEF_POA': 0.25,
                                 'DEF_STEAL': 0.2,
                                 'ENDURANCE': 0.15,
                                 'PHYSICAL': 0.1}},
              
 'drop': {'Lowman_Helper': {'DEF_HELP': 0.35, 'DEF_RIM': 0.25, 'DEF_STEAL': 0.1, 'PHYSICAL': 0.15, 'REB_DR': 0.15},
          'Nail_Helper': {'DEF_HELP': 0.45, 'DEF_POA': 0.2, 'DEF_STEAL': 0.15, 'ENDURANCE': 0.1, 'PHYSICAL': 0.1},
          'PnR_Cover_Big_Drop': {'DEF_HELP': 0.15,
                                 'DEF_POST': 0.15,
                                 'DEF_RIM': 0.35,
                                 'ENDURANCE': 0.05,
                                 'PHYSICAL': 0.1,
                                 'REB_DR': 0.2},
          'PnR_POA_Defender': {'DEF_HELP': 0.1, 'DEF_POA': 0.45, 'DEF_STEAL': 0.1, 'ENDURANCE': 0.15, 'PHYSICAL': 0.2},
          'Weakside_Rotator': {'DEF_HELP': 0.45,
                               'DEF_POA': 0.15,
                               'DEF_STEAL': 0.1,
                               'ENDURANCE': 0.15,
                               'PHYSICAL': 0.05,
                               'REB_DR': 0.1}},
 '블리츠-트랩': {'Lowman_Helper': {'DEF_HELP': 0.35,
                              'DEF_RIM': 0.25,
                              'DEF_STEAL': 0.05,
                              'ENDURANCE': 0.15,
                              'PHYSICAL': 0.1,
                              'REB_DR': 0.1},
            'Nail_Helper': {'DEF_HELP': 0.4, 'DEF_POA': 0.15, 'DEF_STEAL': 0.2, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
            'PnR_Cover_Big_Blitz': {'DEF_HELP': 0.2,
                                    'DEF_POA': 0.2,
                                    'DEF_RIM': 0.05,
                                    'DEF_STEAL': 0.2,
                                    'ENDURANCE': 0.2,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.05},
            'PnR_POA_Blitz': {'DEF_HELP': 0.1, 'DEF_POA': 0.3, 'DEF_STEAL': 0.25, 'ENDURANCE': 0.2, 'PHYSICAL': 0.15},
            'Weakside_Rotator': {'DEF_HELP': 0.35,
                                 'DEF_POA': 0.15,
                                 'DEF_STEAL': 0.15,
                                 'ENDURANCE': 0.25,
                                 'PHYSICAL': 0.05,
                                 'REB_DR': 0.05}},
 '올-스위치': {'Backline_Anchor': {'DEF_HELP': 0.25,
                               'DEF_POST': 0.1,
                               'DEF_RIM': 0.3,
                               'ENDURANCE': 0.05,
                               'PHYSICAL': 0.1,
                               'REB_DR': 0.2},
           'PnR_Cover_Big_Switch': {'DEF_HELP': 0.1,
                                    'DEF_POA': 0.3,
                                    'DEF_POST': 0.15,
                                    'DEF_RIM': 0.15,
                                    'ENDURANCE': 0.1,
                                    'PHYSICAL': 0.2},
           'PnR_POA_Switch': {'DEF_HELP': 0.15,
                              'DEF_POA': 0.3,
                              'DEF_POST': 0.2,
                              'DEF_STEAL': 0.05,
                              'ENDURANCE': 0.1,
                              'PHYSICAL': 0.2},
           'Switch_Wing_Strong': {'DEF_HELP': 0.25,
                                  'DEF_POA': 0.3,
                                  'DEF_STEAL': 0.15,
                                  'ENDURANCE': 0.15,
                                  'PHYSICAL': 0.1,
                                  'REB_DR': 0.05},
           'Switch_Wing_Weak': {'DEF_HELP': 0.3,
                                'DEF_POA': 0.2,
                                'DEF_STEAL': 0.1,
                                'ENDURANCE': 0.1,
                                'PHYSICAL': 0.1,
                                'REB_DR': 0.2}},
 '스위치 1-4': {'Backline_Anchor': {'DEF_HELP': 0.25,
                                'DEF_POST': 0.12,
                                'DEF_RIM': 0.32,
                                'ENDURANCE': 0.05,
                                'PHYSICAL': 0.1,
                                'REB_DR': 0.16},
           'PnR_Cover_Big_Switch_1_4': {'DEF_HELP': 0.18,
                                        'DEF_POA': 0.08,
                                        'DEF_POST': 0.22,
                                        'DEF_RIM': 0.22,
                                        'ENDURANCE': 0.1,
                                        'PHYSICAL': 0.15,
                                        'REB_DR': 0.05},
           'PnR_POA_Switch_1_4': {'DEF_HELP': 0.15,
                                  'DEF_POA': 0.32,
                                  'DEF_POST': 0.18,
                                  'DEF_STEAL': 0.05,
                                  'ENDURANCE': 0.12,
                                  'PHYSICAL': 0.18},
           'Switch_Wing_Strong_1_4': {'DEF_HELP': 0.25,
                                      'DEF_POA': 0.3,
                                      'DEF_STEAL': 0.15,
                                      'ENDURANCE': 0.15,
                                      'PHYSICAL': 0.1,
                                      'REB_DR': 0.05},
           'Switch_Wing_Weak_1_4': {'DEF_HELP': 0.3,
                                    'DEF_POA': 0.2,
                                    'DEF_STEAL': 0.1,
                                    'ENDURANCE': 0.1,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.2}},
 '헷지-쇼앤리커버': {'Lowman_Helper': {'DEF_HELP': 0.35,
                                'DEF_RIM': 0.2,
                                'DEF_STEAL': 0.05,
                                'ENDURANCE': 0.15,
                                'PHYSICAL': 0.1,
                                'REB_DR': 0.15},
              'Nail_Helper': {'DEF_HELP': 0.4, 'DEF_POA': 0.2, 'DEF_STEAL': 0.15, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
              'PnR_Cover_Big_HedgeRecover': {'DEF_HELP': 0.15,
                                             'DEF_POA': 0.25,
                                             'DEF_RIM': 0.15,
                                             'DEF_STEAL': 0.05,
                                             'ENDURANCE': 0.2,
                                             'PHYSICAL': 0.15,
                                             'REB_DR': 0.05},
              'PnR_POA_Defender': {'DEF_HELP': 0.1,
                                   'DEF_POA': 0.45,
                                   'DEF_STEAL': 0.1,
                                   'ENDURANCE': 0.2,
                                   'PHYSICAL': 0.15},
              'Weakside_Rotator': {'DEF_HELP': 0.4,
                                   'DEF_POA': 0.15,
                                   'DEF_STEAL': 0.1,
                                   'ENDURANCE': 0.2,
                                   'PHYSICAL': 0.05,
                                   'REB_DR': 0.1}},
 '앳-더-레벨': {'Lowman_Helper': {'DEF_HELP': 0.35,
                           'DEF_RIM': 0.2,
                           'DEF_STEAL': 0.05,
                           'ENDURANCE': 0.15,
                           'PHYSICAL': 0.1,
                           'REB_DR': 0.15},
                 'Nail_Helper': {'DEF_HELP': 0.4,
                                'DEF_POA': 0.2,
                                'DEF_STEAL': 0.15,
                                'ENDURANCE': 0.15,
                                'PHYSICAL': 0.1},
                 'PnR_Cover_Big_AtTheLevel': {'DEF_HELP': 0.15,
                                             'DEF_POA': 0.3,
                                             'DEF_RIM': 0.1,
                                             'DEF_STEAL': 0.05,
                                             'ENDURANCE': 0.25,
                                             'PHYSICAL': 0.1,
                                             'REB_DR': 0.05},
                 'PnR_POA_AtTheLevel': {'DEF_HELP': 0.1,
                                      'DEF_POA': 0.45,
                                      'DEF_STEAL': 0.1,
                                      'ENDURANCE': 0.25,
                                      'PHYSICAL': 0.1},
                 'Weakside_Rotator': {'DEF_HELP': 0.4,
                                      'DEF_POA': 0.15,
                                      'DEF_STEAL': 0.1,
                                      'ENDURANCE': 0.2,
                                      'PHYSICAL': 0.05,
                                      'REB_DR': 0.1}}}
