# =============================================================================
# [DATA FILE ONLY]  (quality_data 패키지로 분리됨)
# 이 파일은 로직이 아니라 '튜닝 테이블/상수'만 담는 **데이터 모듈**입니다.
# 로직 파일: quality.py
# =============================================================================

from __future__ import annotations

from typing import Dict

# scheme -> base_action -> outcome -> label
SCHEME_BASE_OUTCOME_LABELS: Dict[str, Dict[str, Dict[str, str]]] = {'2-3 존디펜스': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'DHO': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_3_CS': 'weak',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                        'PASS_EXTRA': 'neutral',
                        'PASS_KICKOUT': 'neutral',
                        'SHOT_3_OD': 'Neutral',
                        'SHOT_MID_PU': 'Neutral',
                        'SHOT_RIM_CONTACT': 'tight',
                        'SHOT_RIM_DUNK': 'Neutral',
                        'SHOT_RIM_LAYUP': 'tight',
                        'SHOT_TOUCH_FLOATER': 'Neutral',
                        'TO_CHARGE': 'Neutral',
                        'TO_HANDLE_LOSS': 'Neutral'},
              'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                            'PASS_EXTRA': 'Neutral',
                            'PASS_SKIP': 'tight',
                            'SHOT_3_CS': 'Neutral',
                            'SHOT_MID_CS': 'Neutral'},
              'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                           'PASS_EXTRA': 'Neutral',
                           'PASS_KICKOUT': 'weak',
                           'SHOT_3_CS': 'Neutral',
                           'SHOT_MID_CS': 'Neutral'},
              'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'tight',
                          'SHOT_3_CS': 'Neutral',
                          'SHOT_MID_CS': 'Neutral'},
              'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_KICKOUT': 'neutral',
                      'PASS_SHORTROLL': 'Neutral',
                      'SHOT_3_CS': 'neutral',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_DUNK': 'tight',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'PnP': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'neutral',
                      'PASS_KICKOUT': 'neutral',
                      'SHOT_3_CS': 'weak',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_CS': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'tight',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                         'PASS_EXTRA': 'neutral',
                         'PASS_KICKOUT': 'neutral',
                         'PASS_SKIP': 'tight',
                         'SHOT_POST': 'Neutral',
                         'SHOT_RIM_CONTACT': 'tight',
                         'TO_HANDLE_LOSS': 'Neutral'},
              'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'weak', 'SHOT_MID_CS': 'Neutral'},
              'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                  'PASS_EXTRA': 'Neutral',
                                  'PASS_KICKOUT': 'Neutral',
                                  'SHOT_3_CS': 'Neutral',
                                  'SHOT_3_OD': 'Neutral',
                                  'SHOT_RIM_CONTACT': 'Neutral',
                                  'SHOT_RIM_DUNK': 'Neutral',
                                  'SHOT_RIM_LAYUP': 'Neutral',
                                  'SHOT_TOUCH_FLOATER': 'Neutral',
                                  'TO_HANDLE_LOSS': 'Neutral'}},
 'drop': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'Neutral',
                  'SHOT_RIM_CONTACT': 'tight',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'Neutral',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'DHO': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'tight',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'Neutral',
                  'SHOT_3_CS': 'Neutral',
                  'SHOT_3_OD': 'tight',
                  'SHOT_MID_PU': 'weak',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_CHARGE': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
          'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'Neutral',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'weak',
                  'SHOT_3_OD': 'tight',
                  'SHOT_MID_PU': 'Neutral',
                  'SHOT_RIM_CONTACT': 'tight',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_CHARGE': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_3_CS': 'weak',
                        'SHOT_MID_CS': 'Neutral'},
          'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_KICKOUT': 'Neutral',
                       'SHOT_3_CS': 'Neutral',
                       'SHOT_MID_CS': 'Neutral'},
          'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_SKIP': 'Neutral',
                      'SHOT_3_CS': 'weak',
                      'SHOT_MID_CS': 'Neutral'},
          'PnR': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'tight',
                  'PASS_KICKOUT': 'weak',
                  'PASS_SHORTROLL': 'Neutral',
                  'SHOT_3_CS': 'weak',
                  'SHOT_3_OD': 'Neutral',
                  'SHOT_MID_PU': 'weak',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'PnP': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'tight',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'weak',
                  'SHOT_3_CS': 'weak',
                  'SHOT_3_OD': 'Neutral',
                  'SHOT_MID_CS': 'weak',
                  'SHOT_MID_PU': 'weak',
                  'SHOT_RIM_CONTACT': 'tight',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_CHARGE': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'PASS_SKIP': 'Neutral',
                     'SHOT_POST': 'Neutral',
                     'SHOT_RIM_CONTACT': 'tight',
                     'TO_HANDLE_LOSS': 'Neutral'},
          'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
          'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                              'PASS_EXTRA': 'Neutral',
                              'PASS_KICKOUT': 'Neutral',
                              'SHOT_3_CS': 'Neutral',
                              'SHOT_3_OD': 'Neutral',
                              'SHOT_RIM_CONTACT': 'Neutral',
                              'SHOT_RIM_DUNK': 'Neutral',
                              'SHOT_RIM_LAYUP': 'Neutral',
                              'SHOT_TOUCH_FLOATER': 'Neutral',
                              'TO_HANDLE_LOSS': 'Neutral'}},
 '블리츠-트랩': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'weak',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_CS': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'tight'},
            'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
            'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'weak',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_CHARGE': 'Neutral',
                    'TO_HANDLE_LOSS': 'tight'},
            'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'Neutral',
                          'SHOT_3_CS': 'weak',
                          'SHOT_MID_CS': 'Neutral'},
            'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_KICKOUT': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'tight'},
            'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_3_CS': 'weak',
                        'SHOT_MID_CS': 'Neutral'},
            'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_KICKOUT': 'weak',
                    'PASS_SHORTROLL': 'weak',
                    'SHOT_3_CS': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'tight',
                    'TO_HANDLE_LOSS': 'tight'},
            'PnP': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'weak',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_CS': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_CS': 'weak',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'tight',
                    'TO_CHARGE': 'Neutral',
                    'TO_HANDLE_LOSS': 'tight'},
            'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                       'PASS_EXTRA': 'weak',
                       'PASS_KICKOUT': 'weak',
                       'PASS_SKIP': 'weak',
                       'SHOT_POST': 'tight',
                       'SHOT_RIM_CONTACT': 'tight',
                       'TO_HANDLE_LOSS': 'tight'},
            'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
            'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                'PASS_EXTRA': 'Neutral',
                                'PASS_KICKOUT': 'Neutral',
                                'SHOT_3_CS': 'Neutral',
                                'SHOT_3_OD': 'Neutral',
                                'SHOT_RIM_CONTACT': 'Neutral',
                                'SHOT_RIM_DUNK': 'Neutral',
                                'SHOT_RIM_LAYUP': 'Neutral',
                                'SHOT_TOUCH_FLOATER': 'Neutral',
                                'TO_HANDLE_LOSS': 'Neutral'}},
 '올-스위치': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_EXTRA': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'SHOT_RIM_CONTACT': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                   'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_EXTRA': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'SHOT_3_CS': 'tight',
                   'SHOT_3_OD': 'Neutral',
                   'SHOT_MID_PU': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'SHOT_3_OD': 'Neutral',
                     'SHOT_MID_PU': 'Neutral',
                     'SHOT_RIM_CONTACT': 'Neutral',
                     'SHOT_RIM_DUNK': 'Neutral',
                     'SHOT_RIM_LAYUP': 'Neutral',
                     'SHOT_TOUCH_FLOATER': 'Neutral',
                     'TO_CHARGE': 'tight',
                     'TO_HANDLE_LOSS': 'Neutral'},
           'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                   'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_EXTRA': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'SHOT_3_OD': 'Neutral',
                   'SHOT_MID_PU': 'Neutral',
                   'SHOT_RIM_CONTACT': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_CHARGE': 'tight',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_SKIP': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'Neutral'},
           'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_KICKOUT': 'Neutral',
                        'SHOT_3_CS': 'Neutral',
                        'SHOT_MID_CS': 'Neutral'},
           'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_SKIP': 'Neutral',
                       'SHOT_3_CS': 'Neutral',
                       'SHOT_MID_CS': 'Neutral'},
           'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                   'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'PASS_SHORTROLL': 'Neutral',
                   'SHOT_3_CS': 'Neutral',
                   'SHOT_3_OD': 'Neutral',
                   'SHOT_MID_PU': 'Neutral',
            'SHOT_RIM_DUNK': 'Neutral',
            'SHOT_RIM_LAYUP': 'Neutral',
            'SHOT_TOUCH_FLOATER': 'Neutral',
            'TO_HANDLE_LOSS': 'Neutral'},
    'PnP': {'FOUL_DRAW_JUMPER': 'tight',
            'FOUL_DRAW_RIM': 'Neutral',
            'PASS_EXTRA': 'Neutral',
            'PASS_KICKOUT': 'Neutral',
            'SHOT_3_CS': 'Neutral',
            'SHOT_3_OD': 'Neutral',
            'SHOT_MID_CS': 'Neutral',
            'SHOT_MID_PU': 'Neutral',
            'SHOT_RIM_CONTACT': 'Neutral',
            'SHOT_RIM_DUNK': 'Neutral',
            'SHOT_RIM_LAYUP': 'Neutral',
            'SHOT_TOUCH_FLOATER': 'Neutral',
            'TO_CHARGE': 'Neutral',
            'TO_HANDLE_LOSS': 'Neutral'},
    'PostUp': {'FOUL_DRAW_POST': 'Neutral',
               'PASS_EXTRA': 'Neutral',
               'PASS_KICKOUT': 'Neutral',
                      'PASS_SKIP': 'Neutral',
                      'SHOT_POST': 'Neutral',
                      'SHOT_RIM_CONTACT': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
           'SpotUp': {'FOUL_DRAW_JUMPER': 'tight', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
           'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                               'PASS_EXTRA': 'Neutral',
                               'PASS_KICKOUT': 'Neutral',
                               'SHOT_3_CS': 'Neutral',
                               'SHOT_3_OD': 'Neutral',
                               'SHOT_RIM_CONTACT': 'Neutral',
                               'SHOT_RIM_DUNK': 'Neutral',
                               'SHOT_RIM_LAYUP': 'Neutral',
                               'SHOT_TOUCH_FLOATER': 'Neutral',
                               'TO_HANDLE_LOSS': 'Neutral'}},
 '스위치 1-4': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_3_CS': 'tight',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'tight',
                      'TO_HANDLE_LOSS': 'Neutral'},
            'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_3_OD': 'Neutral',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_CONTACT': 'Neutral',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_CHARGE': 'tight',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'Neutral',
                          'SHOT_3_CS': 'Neutral',
                          'SHOT_MID_CS': 'Neutral'},
            'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_KICKOUT': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'Neutral'},
            'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_3_CS': 'Neutral',
                        'SHOT_MID_CS': 'Neutral'},
            'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'PASS_SHORTROLL': 'Neutral',
                    'SHOT_3_CS': 'Neutral',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'PnP': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_3_CS': 'Neutral',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_CS': 'Neutral',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_CONTACT': 'Neutral',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_CHARGE': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'PostUp': {'FOUL_DRAW_POST': 'weak',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_KICKOUT': 'Neutral',
                       'PASS_SKIP': 'Neutral',
                       'SHOT_POST': 'weak',
                       'SHOT_RIM_CONTACT': 'Neutral',
                       'TO_HANDLE_LOSS': 'Neutral'},
            'SpotUp': {'FOUL_DRAW_JUMPER': 'tight',
                       'SHOT_3_CS': 'Neutral',
                       'SHOT_MID_CS': 'Neutral'},
            'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                'PASS_EXTRA': 'Neutral',
                                'PASS_KICKOUT': 'Neutral',
                                'SHOT_3_CS': 'Neutral',
                                'SHOT_3_OD': 'Neutral',
                                'SHOT_RIM_CONTACT': 'Neutral',
                                'SHOT_RIM_DUNK': 'Neutral',
                                'SHOT_RIM_LAYUP': 'Neutral',
                                'SHOT_TOUCH_FLOATER': 'Neutral',
                                'TO_HANDLE_LOSS': 'Neutral'}},
 '헷지-쇼앤리커버': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_3_CS': 'Neutral',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
              'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_KICKOUT': 'Neutral',
                        'SHOT_3_OD': 'tight',
                        'SHOT_MID_PU': 'tight',
                        'SHOT_RIM_CONTACT': 'tight',
                        'SHOT_RIM_DUNK': 'Neutral',
                        'SHOT_RIM_LAYUP': 'tight',
                        'SHOT_TOUCH_FLOATER': 'Neutral',
                        'TO_CHARGE': 'Neutral',
                        'TO_HANDLE_LOSS': 'tight'},
              'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
              'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                            'PASS_EXTRA': 'Neutral',
                            'PASS_SKIP': 'Neutral',
                            'SHOT_3_CS': 'Neutral',
                            'SHOT_MID_CS': 'Neutral'},
              'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                           'PASS_EXTRA': 'Neutral',
                           'PASS_KICKOUT': 'Neutral',
                           'SHOT_3_CS': 'Neutral',
                           'SHOT_MID_CS': 'tight'},
              'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'Neutral',
                          'SHOT_3_CS': 'weak',
                          'SHOT_MID_CS': 'Neutral'},
              'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'PASS_SHORTROLL': 'weak',
                      'SHOT_3_CS': 'Neutral',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                         'SHOT_RIM_DUNK': 'Neutral',
                         'SHOT_RIM_LAYUP': 'Neutral',
                         'SHOT_TOUCH_FLOATER': 'Neutral',
                         'TO_HANDLE_LOSS': 'tight'},
               'PnP': {'FOUL_DRAW_JUMPER': 'tight',
                       'FOUL_DRAW_RIM': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_KICKOUT': 'Neutral',
                       'SHOT_3_CS': 'weak',
                       'SHOT_3_OD': 'tight',
                       'SHOT_MID_CS': 'Neutral',
                       'SHOT_MID_PU': 'tight',
                       'SHOT_RIM_CONTACT': 'Neutral',
                       'SHOT_RIM_DUNK': 'Neutral',
                       'SHOT_RIM_LAYUP': 'Neutral',
                       'SHOT_TOUCH_FLOATER': 'Neutral',
                       'TO_CHARGE': 'Neutral',
                       'TO_HANDLE_LOSS': 'tight'},
               'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_KICKOUT': 'Neutral',
                         'PASS_SKIP': 'Neutral',
                         'SHOT_POST': 'Neutral',
                         'SHOT_RIM_CONTACT': 'tight',
                         'TO_HANDLE_LOSS': 'Neutral'},
              'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'weak', 'SHOT_MID_CS': 'Neutral'},
              'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                  'PASS_EXTRA': 'Neutral',
                                  'PASS_KICKOUT': 'Neutral',
                                  'SHOT_3_CS': 'Neutral',
                                  'SHOT_3_OD': 'Neutral',
                                  'SHOT_RIM_CONTACT': 'Neutral',
                                  'SHOT_RIM_DUNK': 'Neutral',
                                  'SHOT_RIM_LAYUP': 'Neutral',
                                  'SHOT_TOUCH_FLOATER': 'Neutral',
                                  'TO_HANDLE_LOSS': 'Neutral'}},
 '앳-더-레벨': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
         'PASS_EXTRA': 'Neutral',
         'PASS_KICKOUT': 'Neutral',
         'SHOT_RIM_CONTACT': 'tight',
         'SHOT_RIM_DUNK': 'Neutral',
         'SHOT_RIM_LAYUP': 'Neutral',
         'SHOT_TOUCH_FLOATER': 'Neutral',
         'TO_HANDLE_LOSS': 'Neutral'},
 'DHO': {'FOUL_DRAW_JUMPER': 'tight',
         'FOUL_DRAW_RIM': 'Neutral',
         'PASS_EXTRA': 'Neutral',
         'PASS_KICKOUT': 'Neutral',
         'RESET_REDO_DHO': 'Neutral',
         'SHOT_3_CS': 'Neutral',
         'SHOT_3_OD': 'tough',
         'SHOT_MID_PU': 'tough',
         'SHOT_POST': 'Neutral',
         'SHOT_RIM_DUNK': 'Neutral',
         'SHOT_RIM_LAYUP': 'Neutral',
         'SHOT_TOUCH_FLOATER': 'Neutral',
         'TO_CHARGE': 'Neutral',
         'TO_HANDLE_LOSS': 'tight'},
 'Drive': {'FOUL_DRAW_RIM': 'Neutral',
           'PASS_EXTRA': 'Neutral',
           'PASS_KICKOUT': 'Neutral',
           'SHOT_3_OD': 'tough',
           'SHOT_MID_PU': 'tough',
           'SHOT_RIM_CONTACT': 'Neutral',
           'SHOT_RIM_DUNK': 'Neutral',
           'SHOT_RIM_LAYUP': 'tight',
           'SHOT_TOUCH_FLOATER': 'tight',
           'TO_CHARGE': 'Neutral',
           'TO_HANDLE_LOSS': 'tight'},
 'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
               'PASS_EXTRA': 'Neutral',
               'PASS_SKIP': 'Neutral',
               'SHOT_3_CS': 'weak',
               'SHOT_MID_CS': 'Neutral'},
 'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
              'PASS_EXTRA': 'weak',
              'PASS_KICKOUT': 'weak',
              'SHOT_3_CS': 'weak',
              'SHOT_MID_CS': 'Neutral'},
 'ISO': {'FOUL_DRAW_JUMPER': 'Neutral',
         'FOUL_DRAW_RIM': 'Neutral',
         'PASS_EXTRA': 'Neutral',
         'PASS_KICKOUT': 'Neutral',
         'SHOT_3_OD': 'tough',
         'SHOT_MID_PU': 'tough',
         'SHOT_RIM_CONTACT': 'Neutral',
         'SHOT_RIM_DUNK': 'Neutral',
         'SHOT_RIM_LAYUP': 'tight',
         'SHOT_TOUCH_FLOATER': 'tight',
         'TO_CHARGE': 'tight',
         'TO_HANDLE_LOSS': 'tight'},
 'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
             'PASS_EXTRA': 'Neutral',
             'PASS_SKIP': 'Neutral',
             'SHOT_3_CS': 'weak',
             'SHOT_MID_CS': 'Neutral'},
 'PnP': {'FOUL_DRAW_JUMPER': 'tight',
         'FOUL_DRAW_RIM': 'Neutral',
         'PASS_EXTRA': 'weak',
         'PASS_KICKOUT': 'weak',
         'SHOT_3_CS': 'Neutral',
         'SHOT_3_OD': 'tough',
         'SHOT_MID_CS': 'Neutral',
         'SHOT_MID_PU': 'tough',
         'SHOT_RIM_DUNK': 'Neutral',
         'SHOT_RIM_LAYUP': 'Neutral',
         'SHOT_TOUCH_FLOATER': 'Neutral',
         'TO_HANDLE_LOSS': 'tight'},
 'PnR': {'FOUL_DRAW_JUMPER': 'tight',
         'FOUL_DRAW_RIM': 'Neutral',
         'PASS_KICKOUT': 'weak',
         'PASS_SHORTROLL': 'Neutral',
         'RESET_HUB': 'Neutral',
         'RESET_RESREEN': 'Neutral',
         'SHOT_3_CS': 'weak',
         'SHOT_3_OD': 'tough',
         'SHOT_MID_PU': 'tough',
         'SHOT_RIM_CONTACT': 'Neutral',
         'SHOT_RIM_DUNK': 'Neutral',
         'SHOT_RIM_LAYUP': 'tight',
         'SHOT_TOUCH_FLOATER': 'tight',
         'TO_HANDLE_LOSS': 'Neutral'},
 'PostUp': {'FOUL_DRAW_RIM': 'Neutral',
            'PASS_EXTRA': 'Neutral',
            'PASS_SKIP': 'Neutral',
            'SHOT_POST': 'Neutral',
            'SHOT_RIM_CONTACT': 'tight',
            'TO_HANDLE_LOSS': 'Neutral'},
 'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral',
            'SHOT_3_CS': 'weak',
            'SHOT_MID_CS': 'Neutral'},
 'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral', 'PASS_EXTRA': 'Neutral', 'PASS_KICKOUT': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_3_OD': 'Neutral', 'SHOT_RIM_CONTACT': 'Neutral', 'SHOT_RIM_DUNK': 'Neutral', 'SHOT_RIM_LAYUP': 'Neutral', 'SHOT_TOUCH_FLOATER': 'Neutral', 'TO_HANDLE_LOSS': 'Neutral'}}}
