from __future__ import annotations

from typing import Dict



# -------------------------
# Action outcome priors (include fouls)
# -------------------------

ACTION_OUTCOME_PRIORS: Dict[str, Dict[str, float]] = {
    "PnR": {
        "SHOT_RIM_DUNK": 0.1,
        "SHOT_RIM_LAYUP": 0.3,
        "SHOT_RIM_CONTACT": 0.08,
        "SHOT_POST": 0.03,
        "SHOT_TOUCH_FLOATER": 0.11,
        "SHOT_MID_PU": 0.1,
        "SHOT_3_CS": 0.07,
        "SHOT_3_OD": 0.10,
        "PASS_KICKOUT": 0.15,
        "PASS_SHORTROLL": 0.155,
        "FOUL_DRAW_JUMPER": 0.08,
        "FOUL_DRAW_RIM": 0.12,
        "FOUL_REACH_TRAP": 0.1,
        "TO_HANDLE_LOSS": 0.09,
        "TO_CHARGE": 0.02,
        "RESET_RESREEN": 0.059,
        "RESET_HUB": 0.03,
    },
    "PnP": {
        "SHOT_RIM_DUNK": 0.015,
        "SHOT_RIM_LAYUP": 0.17,
        "SHOT_RIM_CONTACT": 0.03,
        "SHOT_TOUCH_FLOATER": 0.08,
        "SHOT_MID_PU": 0.07,
        "SHOT_MID_CS": 0.09,
        "SHOT_3_CS": 0.29,
        "SHOT_3_OD": 0.08,
        "PASS_KICKOUT": 0.15,
        "PASS_EXTRA": 0.09,
        "FOUL_DRAW_JUMPER": 0.06,
        "FOUL_DRAW_RIM": 0.04,
        "FOUL_REACH_TRAP": 0.01,
        "TO_HANDLE_LOSS": 0.08,
        "TO_CHARGE": 0.02,
        "RESET_RESREEN": 0.055,
        "RESET_HUB": 0.035,
    },
    "DHO": {
        "SHOT_RIM_DUNK": 0.07,
        "SHOT_RIM_LAYUP": 0.29,
        "SHOT_TOUCH_FLOATER": 0.15,
        "SHOT_POST": 0.03,
        "SHOT_MID_PU": 0.04,
        "SHOT_3_CS": 0.13,
        "SHOT_3_OD": 0.10,
        "PASS_EXTRA": 0.145,
        "PASS_KICKOUT": 0.165,
        "FOUL_DRAW_JUMPER": 0.03,
        "FOUL_DRAW_RIM": 0.05,
        "FOUL_REACH_TRAP": 0.02,
        "TO_HANDLE_LOSS": 0.07,
        "TO_CHARGE": 0.022,
        "RESET_REDO_DHO": 0.094,
    },
    "Drive": {
        "SHOT_RIM_CONTACT": 0.35,
        "SHOT_RIM_DUNK": 0.27,
        "SHOT_RIM_LAYUP": 0.57,
        "SHOT_POST": 0.02,
        "SHOT_TOUCH_FLOATER": 0.11,
        "SHOT_MID_PU": 0.015,
        "SHOT_3_OD": 0.04,
        "PASS_EXTRA": 0.11,
        "PASS_KICKOUT": 0.16,
        "FOUL_DRAW_RIM": 0.15,
        "FOUL_DRAW_JUMPER": 0.03,
        "FOUL_REACH_TRAP": 0.03,
        "TO_CHARGE": 0.025,
        "TO_HANDLE_LOSS": 0.1,
        "RESET_HUB": 0.049,
    },
    "ISO": {
        "SHOT_RIM_CONTACT": 0.2,
        "SHOT_RIM_DUNK": 0.08,
        "SHOT_RIM_LAYUP": 0.18,
        "SHOT_POST": 0.02,
        "SHOT_TOUCH_FLOATER": 0.09,
        "SHOT_MID_PU": 0.32,
        "SHOT_3_OD": 0.25,
        "PASS_EXTRA": 0.06,
        "PASS_KICKOUT": 0.08,
        "FOUL_DRAW_RIM": 0.13,
        "FOUL_DRAW_JUMPER": 0.07,
        "FOUL_REACH_TRAP": 0.012,
        "TO_CHARGE": 0.02,
        "TO_HANDLE_LOSS": 0.1,
        "RESET_HUB": 0.07,
    },
    "Kickout": {
        "SHOT_MID_CS": 0.04,
        "SHOT_MID_PU": 0.07,
        "SHOT_3_CS": 0.29,
        "SHOT_3_OD": 0.12,
        "PASS_EXTRA": 0.16,
        "PASS_SKIP": 0.105,
        "FOUL_DRAW_JUMPER": 0.05,
        "FOUL_REACH_TRAP": 0.005,
        "TO_HANDLE_LOSS": 0.03,
        "RESET_HUB": 0.078,
    },
    "ExtraPass": {
        "SHOT_MID_CS": 0.05,
        "SHOT_MID_PU": 0.06,
        "SHOT_3_CS": 0.22,
        "SHOT_3_OD": 0.07,
        "PASS_EXTRA": 0.20,
        "PASS_SKIP": 0.18,
        "FOUL_DRAW_JUMPER": 0.04,
        "FOUL_REACH_TRAP": 0.005,
        "TO_HANDLE_LOSS": 0.03,
        "RESET_HUB": 0.215,
    },
    "PostUp": {
        "SHOT_POST": 0.56,
        "SHOT_MID_PU": 0.06,
        "PASS_EXTRA": 0.08,
        "PASS_KICKOUT": 0.08,
        "PASS_SKIP": 0.085,
        "FOUL_DRAW_POST": 0.17,
        "TO_HANDLE_LOSS": 0.09,
        "TO_CHARGE": 0.017,
        "RESET_POST_OUT": 0.078,
    },
    "HornsSet": {
        "SHOT_RIM_CONTACT": 0.09,
        "SHOT_RIM_DUNK": 0.08,
        "SHOT_RIM_LAYUP": 0.18,
        "PASS_KICKOUT": 0.175,
        "SHOT_MID_CS": 0.06,
        "SHOT_MID_PU": 0.06,
        "SHOT_3_CS": 0.19,
        "SHOT_3_OD": 0.08,
        "PASS_EXTRA": 0.2,
        "FOUL_DRAW_JUMPER": 0.03,
        "FOUL_DRAW_RIM": 0.13,
        "TO_HANDLE_LOSS": 0.06,
        "TO_CHARGE": 0.016,
        "RESET_HUB": 0.115,
    },
    "SpotUp": {
        "SHOT_MID_CS": 0.13,
        "SHOT_3_CS": 0.38,
        "SHOT_3_OD": 0.06,
        "SHOT_MID_PU": 0.07,
        "FOUL_DRAW_JUMPER": 0.06,
        "TO_HANDLE_LOSS": 0.04,
        "RESET_HUB": 0.189,
    },
    "Cut": {
        "SHOT_RIM_CONTACT": 0.15,
        "SHOT_RIM_DUNK": 0.18,
        "SHOT_RIM_LAYUP": 0.45,
        "SHOT_TOUCH_FLOATER": 0.06,
        "PASS_EXTRA": 0.06,
        "PASS_KICKOUT": 0.1,
        "FOUL_DRAW_RIM": 0.15,
        "TO_HANDLE_LOSS": 0.06,
        "TO_CHARGE": 0.017,
        "RESET_HUB": 0.109,
    },
    "TransitionEarly": {
        "SHOT_RIM_CONTACT": 0.29,
        "SHOT_RIM_DUNK": 0.21,
        "SHOT_RIM_LAYUP": 0.38,
        "SHOT_TOUCH_FLOATER": 0.03,
        "SHOT_3_CS": 0.03,
        "SHOT_3_OD": 0.06,
        "PASS_EXTRA": 0.04,
        "PASS_KICKOUT": 0.09,
        "FOUL_DRAW_RIM": 0.16,
        "FOUL_DRAW_JUMPER": 0.07,
        "TO_HANDLE_LOSS": 0.14,
        "TO_CHARGE": 0.05,
        "RESET_HUB": 0.06,
    },
    "QuickShot": {
        "SHOT_MID_PU": 0.3,
        "SHOT_3_OD": 0.4,
        "SHOT_3_CS": 0.01,
        "SHOT_MID_CS": 0.01,
        "FOUL_DRAW_JUMPER": 0.05,
        "TO_HANDLE_LOSS": 0.15,
    },
    "Putback": {
        "SHOT_RIM_LAYUP": 0.55,
        "SHOT_RIM_DUNK": 0.26,
        "SHOT_RIM_CONTACT": 0.17,
        "FOUL_DRAW_RIM": 0.22,
        "TO_HANDLE_LOSS": 0.022,
    },
}
