"""Defense scheme meta tuning tables.

Separated from era.py so tuning can happen without touching runtime config logic.
"""
from __future__ import annotations

DEFENSE_META_PARAMS = {
    "defense_meta_strength": 0.45,
    "defense_meta_clamp_lo": 0.80,
    "defense_meta_clamp_hi": 1.20,
    "defense_meta_temperature": 1.10,
    "defense_meta_floor": 0.03,
    "defense_meta_action_mult_tables": {
        "Drop": {
            "PnR": 0.92,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.95,
            "ISO": 1.00,
            "Kickout": 1.02,
            "ExtraPass": 1.02,
            "SpotUp": 1.00,
            "Cut": 1.03,
            "DHO": 1.00,
            "PostUp": 1.05,
            "HornsSet": 1.02,
        },
        "Switch_Everything": {
            "PnR": 0.85,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.95,
            "ISO": 1.00,
            "Kickout": 1.00,
            "ExtraPass": 1.02,
            "SpotUp": 1.02,
            "Cut": 1.08,
            "DHO": 0.92,
            "PostUp": 1.10,
            "HornsSet": 1.05,
        },
        "Switch_1_4": {
            # 1-4 switch: still discourages simple PnR/DHO triggers, but less extreme than all-switch.
            # Allows more drive attempts vs a backline anchor, and slightly increases post probing.
            "PnR": 0.88,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.97,
            "ISO": 1.00,
            "Kickout": 1.00,
            "ExtraPass": 1.02,
            "SpotUp": 1.02,
            "Cut": 1.05,
            "DHO": 0.95,
            "PostUp": 1.07,
            "HornsSet": 1.04,
        },
        "Hedge_ShowRecover": {
            "PnR": 0.90,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.92,
            "ISO": 1.00,
            "Kickout": 1.05,
            "ExtraPass": 1.05,
            "SpotUp": 1.04,
            "Cut": 1.00,
            "DHO": 0.95,
            "PostUp": 1.00,
            "HornsSet": 1.00,
        },
        "AtTheLevel": {
            "PnR": 0.89,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.92,
            "ISO": 1.00,
            "Kickout": 1.02,
            "ExtraPass": 1.02,
            "SpotUp": 1.03,
            "Cut": 1.02,
            "DHO": 0.92,
            "PostUp": 1.00,
            "HornsSet": 1.02,
        },
        "Blitz_TrapPnR": {
            "PnR": 0.82,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.90,
            "ISO": 1.00,
            "Kickout": 1.08,
            "ExtraPass": 1.08,
            "SpotUp": 1.06,
            "Cut": 1.03,
            "DHO": 1.00,
            "PostUp": 1.00,
            "HornsSet": 1.02,
        },
        "Zone": {
            "PnR": 1.00,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 0.88,
            "ISO": 1.00,
            "Kickout": 1.02,
            "ExtraPass": 1.03,
            "SpotUp": 1.02,
            "Cut": 0.94,
            "DHO": 0.95,
            "PostUp": 0.90,
            "HornsSet": 1.02,
        },
        "Preset_Defense": {
            # Neutral-safe scaffold for preset overlays.
            "PnR": 1.00,
            "PnP": 1.00,
            "TransitionEarly": 1.00,
            "Drive": 1.00,
            "ISO": 1.00,
            "Kickout": 1.00,
            "ExtraPass": 1.00,
            "SpotUp": 1.00,
            "Cut": 1.00,
            "DHO": 1.00,
            "PostUp": 1.00,
            "HornsSet": 1.00,
        },
    },
}

