from __future__ import annotations

from typing import Dict




# -------------------------
# Scheme action weights
# -------------------------

OFF_SCHEME_ACTION_WEIGHTS: Dict[str, Dict[str, float]] = {
    "Spread_HeavyPnR": {
        "PnR": 25,
        "PnP": 9,
        "TransitionEarly": 4,
        "Drive": 9,
        "ISO": 6,
        "Kickout": 8,
        "ExtraPass": 5,
        "SpotUp": 6,
        "Cut": 4,
        "PostUp": 3,
    },
    "Drive_Kick": {
        "Drive": 30,
        "ISO": 6,
        "Kickout": 18,
        "ExtraPass": 12,
        "TransitionEarly": 4,
        "SpotUp": 10,
        "Cut": 8,
        "PnR": 3,
        "DHO": 2,
        "PnP": 3,
        "PostUp": 3,
    },
    "FiveOut": {
        "Drive": 20,
        "ISO": 9,
        "SpotUp": 15,
        "Kickout": 14,
        "TransitionEarly": 4,
        "ExtraPass": 9,
        "Cut": 10,
        "DHO": 8,
        "PnR": 5,
        "PnP": 10,
        "PostUp": 3,
    },
    "Motion_SplitCut": {
        "Cut": 17,
        "ISO": 4,
        "DHO": 8,
        "Drive": 10,
        "Kickout": 6,
        "TransitionEarly": 4,
        "ExtraPass": 6,
        "SpotUp": 6,
        "PnR": 4,
        "PnP": 3,
        "PostUp": 3,
    },
    "DHO_Chicago": {
        "DHO": 16,
        "ISO": 5,
        "Drive": 12,
        "Kickout": 10,
        "ExtraPass": 6,
        "TransitionEarly": 4,
        "SpotUp": 9,
        "PnR": 6,
        "PnP": 4,
        "PostUp": 3,
    },
    "Post_InsideOut": {
        "PostUp": 31,
        "ISO": 5,
        "Kickout": 14,
        "ExtraPass": 8,
        "SpotUp": 12,
        "TransitionEarly": 3,
        "Cut": 8,
        "Drive": 4,
        "DHO": 4,
        "PnP": 3,
    },
    "Horns_Elbow": {
        "HornsSet": 17,
        "ISO": 5,
        "PnR": 12,
        "PnP": 6,
        "DHO": 8,
        "Drive": 10,
        "Kickout": 8,
        "TransitionEarly": 3,
        "ExtraPass": 6,
        "SpotUp": 8,
        "Cut": 6,
        "PostUp": 3,
    },
    "Transition_Early": {
        "TransitionEarly": 17,
        "Drive": 10,
        "Kickout": 10,
        "SpotUp": 9,
        "ExtraPass": 6,
        "Cut": 5,
        "ISO": 3,
        "PnR": 4,
        "PnP": 2,
        "PostUp": 3,
    },
}
