from __future__ import annotations

from typing import Dict




# -------------------------
# Scheme action weights
# -------------------------

OFF_SCHEME_ACTION_WEIGHTS: Dict[str, Dict[str, float]] = {
    "Spread_HeavyPnR": {
        "PnR": 32,
        "PnP": 11,
        "TransitionEarly": 5,
        "Drive": 11,
        "ISO": 8,
        "Kickout": 10,
        "ExtraPass": 6,
        "SpotUp": 8,
        "Cut": 5,
        "PostUp": 4,
    },
    "Drive_Kick": {
        "Drive": 31,
        "ISO": 6,
        "Kickout": 18,
        "ExtraPass": 12,
        "TransitionEarly": 4,
        "SpotUp": 10,
        "Cut": 8,
        "PnR": 3,
        "DHO": 2,
        "PnP": 3,
        "PostUp": 3,
    },
    "FiveOut": {
        "Drive": 19,
        "ISO": 8,
        "SpotUp": 14,
        "Kickout": 13,
        "TransitionEarly": 4,
        "ExtraPass": 8,
        "Cut": 9,
        "DHO": 8,
        "PnR": 5,
        "PnP": 9,
        "PostUp": 3,
    },
    "Motion_SplitCut": {
        "Cut": 24,
        "ISO": 6,
        "DHO": 11,
        "Drive": 14,
        "Kickout": 8,
        "TransitionEarly": 6,
        "ExtraPass": 8,
        "SpotUp": 9,
        "PnR": 6,
        "PnP": 4,
        "PostUp": 4,
    },
    "DHO_Chicago": {
        "DHO": 21,
        "ISO": 7,
        "Drive": 16,
        "Kickout": 14,
        "ExtraPass": 8,
        "TransitionEarly": 5,
        "SpotUp": 12,
        "PnR": 8,
        "PnP": 5,
        "PostUp": 4,
    },
    "Post_InsideOut": {
        "PostUp": 34,
        "ISO": 6,
        "Kickout": 15,
        "ExtraPass": 9,
        "SpotUp": 13,
        "TransitionEarly": 3,
        "Cut": 9,
        "Drive": 4,
        "DHO": 4,
        "PnP": 3,
    },
    "Horns_Elbow": {
        "HornsSet": 18,
        "ISO": 5,
        "PnR": 13,
        "PnP": 7,
        "DHO": 9,
        "Drive": 11,
        "Kickout": 9,
        "TransitionEarly": 3,
        "ExtraPass": 7,
        "SpotUp": 9,
        "Cut": 6,
        "PostUp": 3,
    },
    "Transition_Early": {
        "TransitionEarly": 25,
        "Drive": 14,
        "Kickout": 15,
        "SpotUp": 13,
        "ExtraPass": 9,
        "Cut": 7,
        "ISO": 4,
        "PnR": 6,
        "PnP": 3,
        "PostUp": 4,
    },
    "Preset_Offense": {
        "PnR": 11,
        "PnP": 9,
        "Drive": 11,
        "TransitionEarly": 7,
        "ISO": 7,
        "Kickout": 11,
        "ExtraPass": 10,
        "SpotUp": 11,
        "Cut": 8,
        "DHO": 8,
        "PostUp": 7,
    },
}
