from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class ContractNegotiationError(Exception):
    """Structured error for contract negotiation flows.

    The server layer can map these to HTTP 4xx/5xx while keeping a stable
    machine-readable code for client/UI.
    """

    code: str
    message: str
    details: Optional[Any] = None

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.code}: {self.message}"


# Error codes (stable API surface)
NEGOTIATION_NOT_FOUND = "NEGOTIATION_NOT_FOUND"
NEGOTIATION_BAD_PAYLOAD = "NEGOTIATION_BAD_PAYLOAD"
NEGOTIATION_INVALID_OFFER = "NEGOTIATION_INVALID_OFFER"
NEGOTIATION_INVALID_MODE = "NEGOTIATION_INVALID_MODE"
NEGOTIATION_EXPIRED = "NEGOTIATION_EXPIRED"
NEGOTIATION_CLOSED = "NEGOTIATION_CLOSED"
NEGOTIATION_COMMIT_NOT_ACCEPTED = "NEGOTIATION_COMMIT_NOT_ACCEPTED"
NEGOTIATION_COMMIT_FAILED = "NEGOTIATION_COMMIT_FAILED"
NEGOTIATION_OFFER_EXCEEDS_EXP_AAV_HARD_CAP = "NEGOTIATION_OFFER_EXCEEDS_EXP_AAV_HARD_CAP"
NEGOTIATION_EXTENSION_TYPE_REQUIRED = "NEGOTIATION_EXTENSION_TYPE_REQUIRED"
NEGOTIATION_EXTENSION_TYPE_INVALID = "NEGOTIATION_EXTENSION_TYPE_INVALID"
NEGOTIATION_EXTENSION_NOT_ELIGIBLE = "NEGOTIATION_EXTENSION_NOT_ELIGIBLE"
NEGOTIATION_EXTENSION_WINDOW_CLOSED = "NEGOTIATION_EXTENSION_WINDOW_CLOSED"
NEGOTIATION_EXTENSION_FIRST_YEAR_EXCEEDS_LIMIT = "NEGOTIATION_EXTENSION_FIRST_YEAR_EXCEEDS_LIMIT"
NEGOTIATION_EXTENSION_TOTAL_SEASONS_EXCEEDED = "NEGOTIATION_EXTENSION_TOTAL_SEASONS_EXCEEDED"
NEGOTIATION_EXTENSION_FIXED_RAISE_EXCEEDED = "NEGOTIATION_EXTENSION_FIXED_RAISE_EXCEEDED"
NEGOTIATION_EXTENSION_OPTION_WINDOW_VIOLATION = "NEGOTIATION_EXTENSION_OPTION_WINDOW_VIOLATION"


# Canonical messages for stable UI copy / analytics grouping.
MSG_NEGOTIATION_OFFER_EXCEEDS_EXP_AAV_HARD_CAP = (
    "Offer AAV exceeds league hard cap for player experience bucket"
)
MSG_NEGOTIATION_EXTENSION_TYPE_REQUIRED = "extension_type is required for EXTEND negotiations"
MSG_NEGOTIATION_EXTENSION_TYPE_INVALID = "extension_type must be one of: ROOKIE, VETERAN, DVE"
MSG_NEGOTIATION_EXTENSION_NOT_ELIGIBLE = "Player is not eligible for the requested extension type"
MSG_NEGOTIATION_EXTENSION_WINDOW_CLOSED = "Requested extension is outside the allowed signing window"
MSG_NEGOTIATION_EXTENSION_FIRST_YEAR_EXCEEDS_LIMIT = "Extension first-year salary exceeds allowed limit"
MSG_NEGOTIATION_EXTENSION_TOTAL_SEASONS_EXCEEDED = "Extension total seasons exceeds allowed maximum"
MSG_NEGOTIATION_EXTENSION_FIXED_RAISE_EXCEEDED = "Extension salary curve exceeds fixed raise limit"
MSG_NEGOTIATION_EXTENSION_OPTION_WINDOW_VIOLATION = "Option decision date is outside allowed option window"
